bashrc: prepend rustup toolchain path to $PATH
Rust toolchain binaries like `rust-analyzer`, `cargo`, `rustc`, etc
would give me errors like the following:

```
$ cargo check
error: command failed: 'cargo': No such file or directory (os error 2)
```

I realized this was happening because:

```
$ command -v cargo
/home/pratham/.nix-profile/bin/cargo

$ realpath /home/pratham/.nix-profile/bin/cargo
/nix/store/hav3ba66s36zxh8ljynyw7s6g31b7xbf-rustup-1.28.2/bin/rustup

$ ls -alh /nix/store/hav3ba66s36zxh8ljynyw7s6g31b7xbf-rustup-1.28.2/bin/
total 14M
dr-xr-xr-x  2 root root 4.0K Jan  1  1970 .
dr-xr-xr-x  5 root root   49 Jan  1  1970 ..
lrwxrwxrwx 27 root root    6 Jan  1  1970 cargo -> rustup
lrwxrwxrwx 27 root root    6 Jan  1  1970 cargo-clippy -> rustup
lrwxrwxrwx 27 root root    6 Jan  1  1970 cargo-fmt -> rustup
lrwxrwxrwx 27 root root    6 Jan  1  1970 cargo-miri -> rustup
lrwxrwxrwx 27 root root    6 Jan  1  1970 clippy-driver -> rustup
lrwxrwxrwx 27 root root    6 Jan  1  1970 rls -> rustup
lrwxrwxrwx 27 root root    6 Jan  1  1970 rust-analyzer -> rustup
lrwxrwxrwx 27 root root    6 Jan  1  1970 rustc -> rustup
lrwxrwxrwx 27 root root    6 Jan  1  1970 rustdoc -> rustup
lrwxrwxrwx 27 root root    6 Jan  1  1970 rustfmt -> rustup
lrwxrwxrwx 27 root root    6 Jan  1  1970 rust-gdb -> rustup
lrwxrwxrwx 27 root root    6 Jan  1  1970 rust-gdbgui -> rustup
lrwxrwxrwx 27 root root    6 Jan  1  1970 rust-lldb -> rustup
-r-xr-xr-x  2 root root  16K Jan  1  1970 rustup
-r-xr-xr-x  2 root root  14M Jan  1  1970 .rustup-wrapped
```

And the `cargo` from `pkgs.rustup` was being picked up because the path
`/home/pratham/.nix-profile/bin` preceded the actual path where I use
`rustup` to install the Rust toolchain from first-party sources (Rust
org instead of NixOS)
`/home/pratham/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin`.

```
$ echo $PATH | tr ':' '\n'
/home/pratham/.local/bin
/home/pratham/bin
/run/wrappers/bin
/home/pratham/.local/share/flatpak/exports/bin
/var/lib/flatpak/exports/bin
/home/pratham/.nix-profile/bin
/nix/profile/bin
/home/pratham/.local/state/nix/profile/bin
/etc/profiles/per-user/pratham/bin
/nix/var/nix/profiles/default/bin
/run/current-system/sw/bin
/home/pratham/.cargo/bin
/home/pratham/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin
```

So, prepend that path.